### ISSUE TITLE
Error: Invalid tag for a stake action

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain-indexer#290]
```
86980 block is indexing...
================ sync failed ===================
 Error: Invalid tag for a stake action
    at actionFromRLP (/home/jjg_kodebox_io/indexer/node_modules/codechain-stakeholder-sdk/lib/transactions.js:126:19)
    at Object.actionFromCustom (/home/jjg_kodebox_io/indexer/node_modules/codechain-stakeholder-sdk/lib/transactions.js:64:12)
    at Object.<anonymous> (/home/jjg_kodebox_io/indexer/build/worker/staticFeeDistribution.js:180:69)
    at Generator.next (<anonymous>)
    at /home/jjg_kodebox_io/indexer/build/worker/staticFeeDistribution.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/jjg_kodebox_io/indexer/build/worker/staticFeeDistribution.js:3:12)
    at Object.trackBalanceChangeByTx (/home/jjg_kodebox_io/indexer/build/worker/staticFeeDistribution.js:124:12)
    at Object.<anonymous> (/home/jjg_kodebox_io/indexer/build/worker/cccChange.js:41:48)
    at Generator.next (<anonymous>)
    at fulfilled (/home/jjg_kodebox_io/indexer/build/worker/cccChange.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The stakeholder SDK failed to get ReportDoubleVote action from the custom transaction.

It can be resolved after https://github.com/CodeChain-io/codechain-stakeholder-sdk-js/issues/33 and https://github.com/CodeChain-io/codechain-stakeholder-sdk-js/issues/32

**Comment by joojis** [comment]
The stakeholder SDK failed to get ReportDoubleVote action from the custom transaction.

I made the corgi indexer skip it for now. We need to fix them later.
